### ISSUE TITLE
claferchocoIG chokes on #property * a statement?

### ISSUE THREAD

**Issue by toeklk** [gsdlab/ClaferChocoIG#7] opened 2015-03-24 20:27 UTC
Consider the following clafer model
```
abstract Platform
    price -> int = sum hwComponents.price
    hwComponents -> HWComponent 1..2

abstract HWComponent
    price -> int

abstract Deployment
    price -> int = #platforms * 10 + sum platforms.price // causes chocosolver to choke?
    platforms : Platform 2..3

CAN : HWComponent
   [ price = 10 ]

DO : HWComponent
   [ price = 2 ]

D1: Deployment

// << min D1.price >>
```

Whereas claferIG seems to be able to succesfully generate instances from this model, it seems like the chocoIG fails to do the same.  Removing the `#platforms * 10` clause seems to "solve" the issue

```
[kgad@Klaass-MacBook-Air ~/Workspaces/varies/be.fmtc.costOptimization/Model]$  
 claferIG --maxint 64 ~/Workspaces/varies/be.fmtc.costOptimization/Model/NRE_test.cfr
=== Instance 1 Begin ===

CAN
  price$1 = 10
D1
  price$2 = 32
  platforms$1
    price$3 = 10
    hwComponents$1 = CAN
  platforms$2
    price$4 = 2
    hwComponents$2 = DO
DO
  price$5 = 2

--- Instance 1 End ---


claferIG> q
AlloyIG stream closed.
[kgad@Klaass-MacBook-Air ~/Workspaces/varies/be.fmtc.costOptimization/Model]$  
 java -jar ~/install/clafer/claferchocoig-0.3.9-jar-with-dependencies.jar -n 1 --minint 0 --maxint 64 --file NRE_test.cfr
Clafer Choco Instance Generator and Multi-Objective Optimizer
Compiling the Clafer model...
Running Model...
```

and then the the solver seems to get stuck in an endless loop...

**Comment by JLiangWaterloo** [comment] 2015-03-26 00:49
The Choco backend performs poorly on systems of linear constraints. I intend to improve the performance on linear constraints but it will be a long term goal.

**Comment by toeklk** [comment] 2015-03-26 08:26
Is there a way around this?  `var1 = const * var2` seems to work fine, as do sums, it is the combination of both that seems to cause trouble?
On the other hand, would there (in this particular case) be a possibility to somehow declare that the the price attribute of the Deployment variable is "derived" (in the UML sense), such that the backend knows it should actually not branch on this variable for instance?

**Comment by mantkiew** [comment] 2015-12-11 04:02
I am closing this issue since ClaferChocoIG project is now discontinued. If the issue still persists with the latest release of chocosolver, please [resubmit there](https://github.com/gsdlab/chocosolver/issues).

**Closed by mantkiew** 2015-12-11 04:02 UTC

**Comment by JLiangWaterloo** [comment] 2015-12-11 20:40
I'd forgotten about this issue.

It turns out the issue was actually due to the Fourier-Motzkin elimination optimization. Long story short, it was spinning in an infinite loop because it couldn't detect a fixed-point due to the way linear equations were being eliminated.

The problem is now fixed in the latest chocosolver develop branch.
